"""Data models used by ResearchForge."""

from pydantic import BaseModel, Field


class ResearchTask(BaseModel):
    """A single research task generated by the Planner."""

    topic: str = Field(
        description="Specific aspect of the research question to investigate."
    )

    search_query: str = Field(
        description="Focused web search query for this task."
    )

    rationale: str = Field(
        description="Why this research task is important."
    )


class ResearchPlan(BaseModel):
    """Structured research plan."""

    tasks: list[ResearchTask] = Field(
        min_length=3,
        max_length=4,
        description="Three to four complementary research tasks.",
    )


class Source(BaseModel):
    """A source retrieved from the web."""

    title: str = Field(
        description="Title of the source."
    )

    url: str = Field(
        description="URL of the source."
    )

    snippet: str = Field(
        description="Relevant text retrieved from the source."
    )

    relevance_score: float = Field(
        default=0.0,
        description="Search engine relevance score, when available.",
    )

    source_type: str = Field(
        default="unknown",
        description=(
            "Broad source category such as official, academic, "
            "news, reference, commercial, community, or unknown."
        ),
    )


class ToolTrace(BaseModel):
    """Record of a tool invoked by a Scout."""

    tool_name: str = Field(
        description="Name of the tool invoked."
    )

    input_summary: str = Field(
        description="Short description of the tool input."
    )


class ScoutSummary(BaseModel):
    """Structured evidence analysis produced by a Scout."""

    summary: str = Field(
        description="Concise summary of the evidence."
    )

    key_points: list[str] = Field(
        min_length=2,
        max_length=6,
        description="Important factual points supported by evidence.",
    )

    limitations: list[str] = Field(
        default_factory=list,
        description="Limitations or uncertainty in the evidence.",
    )


class ResearchFinding(BaseModel):
    """Complete finding produced by one Scout."""

    task: str

    summary: str

    key_points: list[str]

    limitations: list[str]

    sources: list[Source]

    tool_trace: list[ToolTrace]


class Analysis(BaseModel):
    """Cross-source analysis produced by the Analyst."""

    overview: str

    key_findings: list[str]

    contradictions: list[str]

    evidence_gaps: list[str]


class Critique(BaseModel):
    """Research quality assessment produced by the Critic."""

    strengths: list[str]

    concerns: list[str]

    missing_evidence: list[str]

    overall_assessment: str


class ReportSection(BaseModel):
    """One section of the final research report."""

    heading: str

    content: str


class ResearchReport(BaseModel):
    """Final structured research report."""

    title: str

    executive_summary: str

    sections: list[ReportSection]

    caveats: list[str]